- become: yes
  hosts: localhost
  name: pre-install

  tasks:
    - name: Retrieve docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
    - name: Retrieve Jenkins repo
      command: '{{ item }}'
      loop:
        - yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    - name: Install Dependency packages
      yum:
        name: '{{ item }}'
        state: present
        update_cache: True
      loop:
        - docker-ce
        - docker-ce-cli
        - docker-compose
        - containerd.io
        - java-1.8.0-openjdk-devel
        - jenkins
        - wget
        - git
        - curl
        - unzip
    - name: Disable CSRF in jenkins
      replace:
        path: /etc/rc.d/init.d/jenkins
        regexp: 'JENKINS_JAVA_OPTIONS'
        replace: JENKINS_JAVA_OPTIONS -Dhudson.security.csrf.GlobalCrumbIssuerConfiguration.DISABLE_CSRF_PROTECTION=true
    - name: Enable the docker and jenkins services
      command: systemctl enable "{{ item }}"
      loop:
        - docker
        - jenkins
    - name: Start docker services
      command: systemctl start "{{ item }}"
      loop:
        - docker
    - name: Add the user 'jenkins' and add it to 'sudo' and docker
      user:
        name: jenkins
        group: docker
    - name: Start jenkins services
      command: systemctl start "{{ item }}"
      loop:
        - jenkins
    - name: Download SonarQube Scanner
      get_url:
        url: https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.0.2311-linux.zip
        dest: /opt
    - name: Unzip SonarQube Scanner
      command: '{{ item }}'
      loop:
        - unzip /opt/sonar-scanner-cli-4.6.0.2311-linux.zip -d /opt
        - mv /opt/sonar-scanner-4.6.0.2311-linux /opt/sonarscanner
    - name: Download AWS CLI
      get_url:
        url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /home/centos
    - name: Move AWS CLI binary
      command: '{{ item }}'
      loop:
        - unzip /home/centos/awscli-exe-linux-x86_64.zip -d /home/centos
        - sh /home/centos/aws/install --bin-dir /usr/bin
    - name: Download jq binary
      get_url:
        url: https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
        dest: /home/centos
    - name: Move the Binary
      command: '{{ item }}'
      loop:
        - mv /home/centos/jq-linux64 /usr/bin/jq
        - chmod +x /usr/bin/jq
    - name: Download SonarQube docker-compose.yml
      get_url:
        url: https://raw.githubusercontent.com/kodekolli/eks-demo-project/main/docker-compose.yml
        dest: /home/centos
    - name: Map count update
      shell: |
        echo 'vm.max_map_count=262144' >> /etc/sysctl.conf
    - name: Install SonarQube Server
      command: '{{ item }}'
      loop:        
        - sysctl -p
        - sysctl -w fs.file-max=65536
        - docker-compose -f /home/centos/docker-compose.yml up -d
        - sleep 5
        - chmod -R 777 /data
        - pip3 install openshift
